In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Read the Adasyn dataset

In [2]:
x_train = pd.read_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/x_train_adasyn.csv')
x_test = pd.read_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/x_test_adasyn.csv')
y_train = pd.read_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/y_train_adasyn.csv')
y_test = pd.read_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/y_test_adasyn.csv')

In [3]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122098 entries, 0 to 122097
Data columns (total 54 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   product_id               122098 non-null  int64
 1   units                    122098 non-null  int64
 2   first_mile               122098 non-null  float64
 3   last_mile                122098 non-null  float64
 4   Total_Dist               122098 non-null  float64
 5   weight                   122098 non-null  int64
 6   material_handling        122098 non-null  int64
 7   origin_port_Athens       122098 non-null  int64
 8   origin_port_Barcelona    122098 non-null  int64
 9   origin_port_Rotterdam    122098 non-null  int64
 10  3pl_v_001                122098 non-null  int64
 11  3pl_v_002                122098 non-null  int64
 12  3pl_v_003                122098 non-null  int64
 13  3pl_v_004                122098 non-null  int64
 14  customs_procedures_CRF   122098 non-null  int64
 15  customs_procedures_DTD   122098 non-null  int64
 16  customs_procedures_DTP   122098 non-null  int64
 17  logistic_hub_Bratislava  122098 non-null  int64
 18  logistic_hub_Dusseldorf  122098 non-null  int64
 19  logistic_hub_Hamburg     122098 non-null  int64
 20  logistic_hub_Liege       122098 non-null  int64
 21  logistic_hub_Lille       122098 non-null  int64
 22  logistic_hub_Rome        122098 non-null  int64
 23  logistic_hub_Venlo       122098 non-null  int64
 24  logistic_hub_Warsaw      122098 non-null  int64
 25  logistic_hub_Zaragoza    122098 non-null  int64
 26  customer_Amsterdam       122098 non-null  int64
 27  customer_Athens          122098 non-null  int64
 28  customer_Barcelona       122098 non-null  int64
 29  customer_Berlin          122098 non-null  int64
 30  customer_Bordeaux        122098 non-null  int64
 31  customer_Bremen          122098 non-null  int64
 32  customer_Bucharest       122098 non-null  int64
 33  customer_Budapest        122098 non-null  int64
 34  customer_Cologne         122098 non-null  int64
 35  customer_Copenhagen      122098 non-null  int64
 36  customer_Hanover         122098 non-null  int64
 37  customer_Helsinki        122098 non-null  int64
 38  customer_Lisbon          122098 non-null  int64
 39  customer_Lyon            122098 non-null  int64
 40  customer_Madrid          122098 non-null  int64
 41  customer_Malm√∂           122098 non-null  int64
 42  customer_Marseille       122098 non-null  int64
 43  customer_Milan           122098 non-null  int64
 44  customer_Munich          122098 non-null  int64
 45  customer_Naples          122098 non-null  int64
 46  customer_Paris           122098 non-null  int64
 47  customer_Porto           122098 non-null  int64
 48  customer_Prague          122098 non-null  int64
 49  customer_Rome            122098 non-null  int64
 50  customer_Stockholm       122098 non-null  int64
 51  customer_Turin           122098 non-null  int64
 52  customer_Valencia        122098 non-null  int64
 53  customer_Vienna          122098 non-null  int64
dtypes: float64(3), int64(51)
memory usage: 50.3 MB

Allocation into respective category

In [4]:
# select numerical variables
numerical_cols = ['units', 'first_mile', 'last_mile', 'Total_Dist', 'weight']
x_train_numerical = x_train[numerical_cols]

# select ordinal variable
ordinal_cols = ['material_handling']
x_train_ordinal = x_train[ordinal_cols]

# select categorical variables
categorical_cols = x_train.columns[7:54]
x_train_categorical = x_train[categorical_cols]

Numerical variables

Check mutual information from numerical variables columns

In [5]:
from sklearn.feature_selection import mutual_info_classif

# Compute mutual information between each feature in X and y
mutual_info1 = mutual_info_classif(x_train_numerical, y_train, random_state=42)

# Create a DataFrame to store the mutual information scores for each feature
mi_df1 = pd.DataFrame({'feature': numerical_cols, 'mi_score': mutual_info1})

# Sort the features by their mutual information scores in descending order
mi_df1 = mi_df1.sort_values(by='mi_score', ascending=False)

# Print the mutual information scores for each feature
mi_df1

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

      feature  mi_score
3  Total_Dist  0.306028
2   last_mile  0.298901
1  first_mile  0.239016
4      weight  0.139332
0       units  0.017997

Check pairwise correlation between numerical variables.

In [6]:
import seaborn as sns
import matplotlib.pyplot as plt

# Selecting the numerical columns from the dataframe
numerical_cols = ['units', 'first_mile', 'last_mile', 'Total_Dist', 'weight']

# Creating the correlation matrix
corr_matrix = x_train[numerical_cols].corr()

# show correlation matrix with numbers
corr_matrix.style.background_gradient(cmap='coolwarm')

Total_Dist is highly collinear with first_mile and last_mile. Total_dist needs to be removed.

Ordinal variables

Check mutual information gain

In [7]:
from sklearn.feature_selection import mutual_info_classif

# Compute mutual information between each feature in X and y
mutual_info2 = mutual_info_classif(x_train_ordinal, y_train, random_state=42)

# Create a DataFrame to store the mutual information scores for each feature
mi_df2 = pd.DataFrame({'feature': ordinal_cols, 'mi_score': mutual_info2})

# Sort the features by their mutual information scores in descending order
mi_df2 = mi_df2.sort_values(by='mi_score', ascending=False)

# Print the mutual information scores for each feature
mi_df2

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

             feature  mi_score
0  material_handling  0.014257

Categorical variables

Mutual Information

In [8]:
from sklearn.feature_selection import mutual_info_classif

# Compute mutual information between each feature in X and y
mutual_info3 = mutual_info_classif(x_train_categorical, y_train, random_state=42)

# Create a DataFrame to store the mutual information scores for each feature
mi_df3 = pd.DataFrame({'feature': categorical_cols, 'mi_score': mutual_info3})

# Sort the features by their mutual information scores in descending order
mi_df3 = mi_df3.sort_values(by='mi_score', ascending=False)

# Print the mutual information scores for each feature
mi_df3

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

                    feature  mi_score
4                 3pl_v_002  0.046733
7    customs_procedures_CRF  0.042339
2     origin_port_Rotterdam  0.041585
16       logistic_hub_Venlo  0.020174
8    customs_procedures_DTD  0.014733
11  logistic_hub_Dusseldorf  0.012847
12     logistic_hub_Hamburg  0.009883
6                 3pl_v_004  0.009562
46          customer_Vienna  0.008214
22          customer_Berlin  0.008183
0        origin_port_Athens  0.007930
36           customer_Milan  0.007726
1     origin_port_Barcelona  0.006740
19       customer_Amsterdam  0.005868
27         customer_Cologne  0.005846
37          customer_Munich  0.005689
13       logistic_hub_Liege  0.005077
17      logistic_hub_Warsaw  0.004964
21       customer_Barcelona  0.004908
39           customer_Paris  0.004533
33          customer_Madrid  0.003745
9    customs_procedures_DTP  0.003557
10  logistic_hub_Bratislava  0.003479
41          customer_Prague  0.003094
5                 3pl_v_003  0.003036
29         customer_Hanover  0.002538
14       logistic_hub_Lille  0.002099
26        customer_Budapest  0.001798
38          customer_Naples  0.001734
42            customer_Rome  0.001698
35       customer_Marseille  0.001647
25       customer_Bucharest  0.001512
43       customer_Stockholm  0.001340
32            customer_Lyon  0.001309
40           customer_Porto  0.001248
44           customer_Turin  0.001017
3                 3pl_v_001  0.001016
45        customer_Valencia  0.000726
28      customer_Copenhagen  0.000554
34           customer_Malm√∂  0.000445
23        customer_Bordeaux  0.000343
15        logistic_hub_Rome  0.000000
18    logistic_hub_Zaragoza  0.000000
31          customer_Lisbon  0.000000
30        customer_Helsinki  0.000000
24          customer_Bremen  0.000000
20          customer_Athens  0.000000

Chi square test for categorical variables

In [11]:
from sklearn.feature_selection import chi2, SelectKBest

# feature selection
def chi2_select_features(X_train, y_train):
  # Set seed to 42
  np.random.seed(42)
  fs = SelectKBest(score_func=chi2, k='all')
  fs.fit(X_train, y_train)
  return fs

def chi2_transform(X_train, X_test, fs):
  X_train_fs = fs.transform(X_train)
  X_test_fs = fs.transform(X_test)
  return X_train_fs, X_test_fs

fs1 = chi2_select_features(x_train_categorical,y_train)

In [12]:
# Create dataframe to store results
results_df = pd.DataFrame(columns=['Feature', 'Chi-Square Score'])

# Loop through each feature and store score
for i in range(len(x_train_categorical.columns)):
    feature = x_train_categorical.columns[i]
    score = fs1.scores_[i]
    results_df = pd.concat([results_df,
                            pd.DataFrame({'Feature': [feature],
                                                      'Chi-Square Score': [score]})])

# Sort results dataframe by Score column in descending order
results_df = results_df.sort_values(by='Chi-Square Score', ascending=False)

# Reset the index without adding the old index as a column
results_df = results_df.reset_index(drop=True)

# Print results dataframe
results_df

                    Feature  Chi-Square Score
0                 3pl_v_002       6282.716847
1    customs_procedures_CRF       6238.363436
2     origin_port_Rotterdam       4170.724987
3        logistic_hub_Venlo       3881.227109
4   logistic_hub_Dusseldorf       2672.433627
5      logistic_hub_Hamburg       2134.597817
6    customs_procedures_DTD       1926.863956
7           customer_Berlin       1723.919189
8            customer_Milan       1606.588180
9                 3pl_v_004       1374.287695
10       origin_port_Athens       1254.947381
11          customer_Vienna       1245.256031
12          customer_Munich       1203.569308
13      logistic_hub_Warsaw       1187.385281
14       customer_Amsterdam       1118.019721
15                3pl_v_003       1012.793565
16         customer_Cologne        906.101495
17       logistic_hub_Liege        829.369340
18          customer_Madrid        751.762887
19       customer_Barcelona        732.660712
20            customer_Rome        617.053833
21    origin_port_Barcelona        599.816521
22         customer_Hanover        553.845683
23       customer_Bucharest        540.530774
24        logistic_hub_Rome        529.399111
25        customer_Budapest        521.795079
26      customer_Copenhagen        503.825348
27           customer_Turin        502.165297
28   customs_procedures_DTP        483.956992
29          customer_Naples        481.566066
30          customer_Bremen        441.404652
31       customer_Stockholm        386.815236
32          customer_Prague        363.203667
33           customer_Malm√∂        300.794280
34        customer_Valencia        299.946485
35           customer_Paris        221.682235
36          customer_Athens        201.216410
37       customer_Marseille        146.194856
38            customer_Lyon        141.434430
39  logistic_hub_Bratislava        114.943660
40        customer_Bordeaux        112.024689
41    logistic_hub_Zaragoza         98.313063
42          customer_Lisbon         92.670601
43        customer_Helsinki         91.572701
44           customer_Porto         70.494297
45                3pl_v_001         70.134722
46       logistic_hub_Lille         11.080175

Final decision is to drop the Total dist rows and product id

In [13]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122098 entries, 0 to 122097
Data columns (total 54 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   product_id               122098 non-null  int64
 1   units                    122098 non-null  int64
 2   first_mile               122098 non-null  float64
 3   last_mile                122098 non-null  float64
 4   Total_Dist               122098 non-null  float64
 5   weight                   122098 non-null  int64
 6   material_handling        122098 non-null  int64
 7   origin_port_Athens       122098 non-null  int64
 8   origin_port_Barcelona    122098 non-null  int64
 9   origin_port_Rotterdam    122098 non-null  int64
 10  3pl_v_001                122098 non-null  int64
 11  3pl_v_002                122098 non-null  int64
 12  3pl_v_003                122098 non-null  int64
 13  3pl_v_004                122098 non-null  int64
 14  customs_procedures_CRF   122098 non-null  int64
 15  customs_procedures_DTD   122098 non-null  int64
 16  customs_procedures_DTP   122098 non-null  int64
 17  logistic_hub_Bratislava  122098 non-null  int64
 18  logistic_hub_Dusseldorf  122098 non-null  int64
 19  logistic_hub_Hamburg     122098 non-null  int64
 20  logistic_hub_Liege       122098 non-null  int64
 21  logistic_hub_Lille       122098 non-null  int64
 22  logistic_hub_Rome        122098 non-null  int64
 23  logistic_hub_Venlo       122098 non-null  int64
 24  logistic_hub_Warsaw      122098 non-null  int64
 25  logistic_hub_Zaragoza    122098 non-null  int64
 26  customer_Amsterdam       122098 non-null  int64
 27  customer_Athens          122098 non-null  int64
 28  customer_Barcelona       122098 non-null  int64
 29  customer_Berlin          122098 non-null  int64
 30  customer_Bordeaux        122098 non-null  int64
 31  customer_Bremen          122098 non-null  int64
 32  customer_Bucharest       122098 non-null  int64
 33  customer_Budapest        122098 non-null  int64
 34  customer_Cologne         122098 non-null  int64
 35  customer_Copenhagen      122098 non-null  int64
 36  customer_Hanover         122098 non-null  int64
 37  customer_Helsinki        122098 non-null  int64
 38  customer_Lisbon          122098 non-null  int64
 39  customer_Lyon            122098 non-null  int64
 40  customer_Madrid          122098 non-null  int64
 41  customer_Malm√∂           122098 non-null  int64
 42  customer_Marseille       122098 non-null  int64
 43  customer_Milan           122098 non-null  int64
 44  customer_Munich          122098 non-null  int64
 45  customer_Naples          122098 non-null  int64
 46  customer_Paris           122098 non-null  int64
 47  customer_Porto           122098 non-null  int64
 48  customer_Prague          122098 non-null  int64
 49  customer_Rome            122098 non-null  int64
 50  customer_Stockholm       122098 non-null  int64
 51  customer_Turin           122098 non-null  int64
 52  customer_Valencia        122098 non-null  int64
 53  customer_Vienna          122098 non-null  int64
dtypes: float64(3), int64(51)
memory usage: 50.3 MB

In [14]:
x_train1 = x_train.drop(['Total_Dist','product_id'], axis = 1)
x_test1 = x_test.drop(['Total_Dist','product_id'], axis = 1)

Export the new x_train1 and the x_test1 file

In [15]:
x_train1.to_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/x_train_adasyn_c.csv', index=False)

In [16]:
x_test1.to_csv('/content/drive/MyDrive/Project/Accenture Supply Chain/Dataset/x_test_adasyn_c.csv', index=False)